version: '3.8'

services:
  addy-art:
    container_name: addy-art
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13777:3000"
    environment:
      - NODE_ENV=production
      - AUTH_TRUST_HOST=true
    env_file:
      - .env
    volumes:
      - ./data:/app/.data:rw
      - ./public/uploads:/app/public/uploads:rw
    user: "root"
    restart: unless-stopped

